# .github/workflows/ci-cd.yml
name: Build, Push, and Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HUB_USERNAME: jeffare9x

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push app-one
        uses: docker/build-push-action@v5
        with:
          context: ./app-one
          file: ./app-one/.dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/app-one:latest

      - name: Build and push app-two
        uses: docker/build-push-action@v5
        with:
          context: ./app-two
          file: ./app-two/.dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/app-two:latest

      - name: Build and push app-three
        uses: docker/build-push-action@v5
        with:
          context: ./app-three
          file: ./app-three/.dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/app-three:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # ADD THIS STEP TO MAKE YOUR FILES AVAILABLE
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=./kubeconfig
          kubectl apply -f ./app-one/deployment.yaml
          kubectl apply -f ./app-two/deployment.yaml
          kubectl apply -f ./app-three/deployment.yaml
          kubectl apply -f ./ingress/ingress.yaml

  verify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # ADD THIS STEP HERE AS WELL
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
          
      - name: Verify Kubernetes Deployments
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=./kubeconfig
          echo "Waiting 15 seconds for resources to be ready..."
          sleep 15
          kubectl get deployments
          kubectl get services
          kubectl get ingress
