name: Automated Deployment of Multiple Apps

# Trigger this pipeline on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    # The job name now includes the app name from the matrix
    name: Build & Deploy ${{ matrix.app }}
    runs-on: self-hosted
    permissions:
     contents: read
     packages: write
    

    strategy:
      # Define a matrix to run this job for each application
      matrix:
        app: [app-one, app-two, app-three]

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      # STEP A: Log in to the container registry (required before pushing)
      - name: 2. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # STEP B: Build the image from the Dockerfile and push it to the registry
      - name: 3. Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # Assumes each app has its own Dockerfile in its own directory
          context: ./${{ matrix.app }}
          push: true
          # Tags the image with the app name and commit SHA
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}:${{ github.sha }}

      - name: 4. Deploy to Kubernetes
        run: |
          echo "Preparing deployment for ${{ matrix.app }}..."
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ./kubeconfig
          export KUBECONFIG=./kubeconfig

          echo "Applying service configuration..."
          kubectl apply -f ./${{ matrix.app }}/service.yaml

          echo "Updating deployment with the new image..."
          kubectl set image deployment/${{ matrix.app }}-deployment ${{ matrix.app }}-container=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}:${{ github.sha }}

          echo "Deployment complete for ${{ matrix.app }}!"
