# .github/workflows/ci-cd.yml
name: Build, Push, and Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_HUB_USERNAME: jeff9x # Your Docker Hub username

jobs:
  # Job 1: Build all Docker images and push them to Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push app-one
        uses: docker/build-push-action@v5
        with:
          context: ./app-one
          file: ./app-one/Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/app-one:latest

      - name: Build and push app-two
        uses: docker/build-push-action@v5
        with:
          context: ./app-two
          file: ./app-two/Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/app-two:latest

      - name: Build and push app-three
        uses: docker/build-push-action@v5
        with:
          context: ./app-three
          file: ./app-three/Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/app-three:latest

  # Job 2: Deploy applications to Kubernetes
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # This job runs only after 'build-and-push' is successful
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          # Write the kubeconfig from secrets to a file
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=./kubeconfig

          # Apply Kubernetes manifests
          kubectl apply -f ./app-one/deployment.yaml
          kubectl apply -f ./app-two/deployment.yaml
          kubectl apply -f ./app-three/deployment.yaml
          kubectl apply -f ./ingress/ingress.yaml

  # Job 3: Verify the deployments
  verify:
    runs-on: ubuntu-latest
    needs: deploy # This job runs only after 'deploy' is successful
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
          
      - name: Verify Kubernetes Deployments
        run: |
          # Write the kubeconfig from secrets to a file
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=./kubeconfig

          echo "Waiting 15 seconds for resources to be ready..."
          sleep 15

          # Verify the status of Kubernetes resources
          kubectl get deployments
          kubectl get services
          kubectl get ingress
